# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PythonProjects\NukePython\smart_review_tool\review_tool_UI\reviewToolUI.ui',
# licensing of 'D:\PythonProjects\NukePython\smart_review_tool\review_tool_UI\reviewToolUI.ui' applies.
#
# Created: Thu Oct  7 23:28:17 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(981, 644)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame = QtWidgets.QFrame(self.frame)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.import_pushbutton = QtWidgets.QPushButton(self.horizontalFrame)
        self.import_pushbutton.setObjectName("import_pushbutton")
        self.horizontalLayout.addWidget(self.import_pushbutton)
        self.save_pushbutton = QtWidgets.QPushButton(self.horizontalFrame)
        self.save_pushbutton.setObjectName("save_pushbutton")
        self.horizontalLayout.addWidget(self.save_pushbutton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pen_icon_label = QtWidgets.QLabel(self.horizontalFrame)
        self.pen_icon_label.setObjectName("pen_icon_label")
        self.horizontalLayout.addWidget(self.pen_icon_label)
        self.brush_size_slider = QtWidgets.QSlider(self.horizontalFrame)
        self.brush_size_slider.setMaximumSize(QtCore.QSize(100, 16777215))
        self.brush_size_slider.setMinimum(10)
        self.brush_size_slider.setMaximum(20)
        self.brush_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brush_size_slider.setObjectName("brush_size_slider")
        self.horizontalLayout.addWidget(self.brush_size_slider)
        self.addtext_pushbutton = QtWidgets.QPushButton(self.horizontalFrame)
        self.addtext_pushbutton.setObjectName("addtext_pushbutton")
        self.horizontalLayout.addWidget(self.addtext_pushbutton)
        self.text_color_pushbutton = QtWidgets.QPushButton(self.horizontalFrame)
        self.text_color_pushbutton.setObjectName("text_color_pushbutton")
        self.horizontalLayout.addWidget(self.text_color_pushbutton)
        self.font_combo_box = QtWidgets.QFontComboBox(self.horizontalFrame)
        self.font_combo_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.font_combo_box.setObjectName("font_combo_box")
        self.horizontalLayout.addWidget(self.font_combo_box)
        self.font_size_combox = QtWidgets.QComboBox(self.horizontalFrame)
        self.font_size_combox.setObjectName("font_size_combox")
        self.horizontalLayout.addWidget(self.font_size_combox)
        self.bold_pushButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.bold_pushButton.setMinimumSize(QtCore.QSize(40, 0))
        self.bold_pushButton.setStyleSheet("")
        self.bold_pushButton.setText("")
        self.bold_pushButton.setObjectName("bold_pushButton")
        self.horizontalLayout.addWidget(self.bold_pushButton)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(3, -1, 10, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalFrame_2 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pen_button = QtWidgets.QPushButton(self.verticalFrame_2)
        self.pen_button.setMinimumSize(QtCore.QSize(40, 40))
        self.pen_button.setText("")
        self.pen_button.setObjectName("pen_button")
        self.horizontalLayout_3.addWidget(self.pen_button)
        self.eraser_button = QtWidgets.QPushButton(self.verticalFrame_2)
        self.eraser_button.setMinimumSize(QtCore.QSize(40, 40))
        self.eraser_button.setText("")
        self.eraser_button.setObjectName("eraser_button")
        self.horizontalLayout_3.addWidget(self.eraser_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setContentsMargins(14, -1, 14, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clear_pushbutton = QtWidgets.QPushButton(self.verticalFrame_2)
        self.clear_pushbutton.setMinimumSize(QtCore.QSize(70, 0))
        self.clear_pushbutton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.clear_pushbutton.setObjectName("clear_pushbutton")
        self.verticalLayout_3.addWidget(self.clear_pushbutton)
        self.color_pushbutton = QtWidgets.QPushButton(self.verticalFrame_2)
        self.color_pushbutton.setMinimumSize(QtCore.QSize(70, 70))
        self.color_pushbutton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.color_pushbutton.setStyleSheet("")
        self.color_pushbutton.setObjectName("color_pushbutton")
        self.verticalLayout_3.addWidget(self.color_pushbutton)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.palette_layout = QtWidgets.QGridLayout()
        self.palette_layout.setContentsMargins(0, 0, -1, 0)
        self.palette_layout.setHorizontalSpacing(10)
        self.palette_layout.setVerticalSpacing(5)
        self.palette_layout.setObjectName("palette_layout")
        self.verticalLayout_6.addLayout(self.palette_layout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.verticalFrame_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.import_pushbutton.setText(QtWidgets.QApplication.translate("Form", "Import", None, -1))
        self.save_pushbutton.setText(QtWidgets.QApplication.translate("Form", "save", None, -1))
        self.pen_icon_label.setText(QtWidgets.QApplication.translate("Form", "Size", None, -1))
        self.addtext_pushbutton.setText(QtWidgets.QApplication.translate("Form", "Add Text", None, -1))
        self.text_color_pushbutton.setText(QtWidgets.QApplication.translate("Form", "Text Color", None, -1))
        self.clear_pushbutton.setText(QtWidgets.QApplication.translate("Form", "Clear", None, -1))
        self.color_pushbutton.setText(QtWidgets.QApplication.translate("Form", "Picker", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:7pt; font-style:italic;\">Delete Text - Del,  Edit Text - Double click</span></p><p align=\"justify\"><span style=\" font-size:7pt;\"><br/></span></p></body></html>", None, -1))

